### ISSUE TITLE
Could you add some screenshots of the ui?

### ISSUE THREAD

**Issue by Tetrax-10** [xbmlz/vite-plugin-solid-markdown#1]

**Comment by xbmlz** [comment]
> _No description provided._

https://github.com/xbmlz/vite-plugin-solid-markdown#import-markdown-as-solid-components

**Comment by Tetrax-10** [comment]
sorry i cant see a screenshot

**Comment by xbmlz** [comment]
> sorry i cant see a screenshot, i might be dumb can you send a png or some image link how it looks like

I have created an online demonstration site, and I hope it can meet your needs.
https://vite-plugin-solid-markdown.netlify.app

**Comment by Tetrax-10** [comment]
Thx @xbmlz this plugin is much better than I expected
