### ISSUE TITLE
Cant install the package?

### ISSUE THREAD

**Issue by DaliborTrampota** [xbmlz/vite-plugin-solid-markdown#2]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! While resolving: koknut-dashboard@0.1.0
npm ERR! Found: vite@4.0.3
npm ERR! node_modules/vite
npm ERR!   dev vite@"^4.0.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^2.0.0 || ^3.0.0-0" from vite-plugin-solid-markdown@0.0.4
npm ERR! node_modules/vite-plugin-solid-markdown
npm ERR!   dev vite-plugin-solid-markdown@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\someone\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\someone\AppData\Local\npm-cache\_logs\2022-12-30T20_49_15_046Z-debug-0.log
PS D:\GitHub\KokNut\KokNutRewrite\Website> npm i vite-plugin-solid-markdown -D
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! While resolving: koknut-dashboard@0.1.0
npm ERR! Found: vite@4.0.3
npm ERR! node_modules/vite
npm ERR!   dev vite@"^4.0.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^2.0.0 || ^3.0.0-0" from vite-plugin-solid-markdown@0.0.4
npm ERR! node_modules/vite-plugin-solid-markdown
npm ERR!   dev vite-plugin-solid-markdown@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\someone\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\someone\AppData\Local\npm-cache\_logs\2022-12-30T20_49_36_127Z-debug-0.log
PS D:\GitHub\KokNut\KokNutRewrite\Website> npm i vite-plugin-solid-markdown   
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: koknut-dashboard@0.1.0
PS D:\GitHub\KokNut\KokNutRewrite\Website> npm i vite-plugin-solid-markdown
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: koknut-dashboard@0.1.0
npm ERR! Found: vite@4.0.3
npm ERR! node_modules/vite
npm ERR!   dev vite@"^4.0.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^2.0.0 || ^3.0.0-0" from vite-plugin-solid-markdown@0.0.4  
npm ERR! node_modules/vite-plugin-solid-markdown
npm ERR!   vite-plugin-solid-markdown@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\someone\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\someone\AppData\Local\npm-cache\_logs\2022-12-30T20_50_43_182Z-debug-0.log

it seems like it doesnt work with vite 4.0.0? is there any way to make it work with it?

**Comment by xbmlz** [comment]
> npm ERR! code ERESOLVE npm ERR! ERESOLVE unable to resolve dependency tree npm ERR! While resolving: koknut-dashboard@0.1.0 npm ERR! Found: vite@4.0.3 npm ERR! node_modules/vite npm ERR! dev vite@"^4.0.3" from the root project npm ERR! npm ERR! Could not resolve dependency: npm ERR! peer vite@"^2.0.0 || ^3.0.0-0" from vite-plugin-solid-markdown@0.0.4 npm ERR! node_modules/vite-plugin-solid-markdown npm ERR! dev vite-plugin-solid-markdown@"*" from the root project npm ERR! npm ERR! Fix the upstream dependency conflict, or retry npm ERR! this command with --force, or --legacy-peer-deps npm ERR! to accept an incorrect (and potentially broken) dependency resolution. npm ERR! npm ERR! See C:\Users\someone\AppData\Local\npm-cache\eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\someone\AppData\Local\npm-cache_logs\2022-12-30T20_49_15_046Z-debug-0.log PS D:\GitHub\KokNut\KokNutRewrite\Website> npm i vite-plugin-solid-markdown -D npm ERR! code ERESOLVE npm ERR! ERESOLVE unable to resolve dependency tree npm ERR! While resolving: koknut-dashboard@0.1.0 npm ERR! Found: vite@4.0.3 npm ERR! node_modules/vite npm ERR! dev vite@"^4.0.3" from the root project npm ERR! npm ERR! Could not resolve dependency: npm ERR! peer vite@"^2.0.0 || ^3.0.0-0" from vite-plugin-solid-markdown@0.0.4 npm ERR! node_modules/vite-plugin-solid-markdown npm ERR! dev vite-plugin-solid-markdown@"*" from the root project npm ERR! npm ERR! Fix the upstream dependency conflict, or retry npm ERR! this command with --force, or --legacy-peer-deps npm ERR! to accept an incorrect (and potentially broken) dependency resolution. npm ERR! npm ERR! See C:\Users\someone\AppData\Local\npm-cache\eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\someone\AppData\Local\npm-cache_logs\2022-12-30T20_49_36_127Z-debug-0.log PS D:\GitHub\KokNut\KokNutRewrite\Website> npm i vite-plugin-solid-markdown npm ERR! code ERESOLVE npm ERR! ERESOLVE unable to resolve dependency tree npm ERR! npm ERR! While resolving: koknut-dashboard@0.1.0 PS D:\GitHub\KokNut\KokNutRewrite\Website> npm i vite-plugin-solid-markdown npm ERR! code ERESOLVE npm ERR! ERESOLVE unable to resolve dependency tree npm ERR! npm ERR! While resolving: koknut-dashboard@0.1.0 npm ERR! Found: vite@4.0.3 npm ERR! node_modules/vite npm ERR! dev vite@"^4.0.3" from the root project npm ERR! npm ERR! Could not resolve dependency: npm ERR! peer vite@"^2.0.0 || ^3.0.0-0" from vite-plugin-solid-markdown@0.0.4 npm ERR! node_modules/vite-plugin-solid-markdown npm ERR! vite-plugin-solid-markdown@"*" from the root project npm ERR! npm ERR! Fix the upstream dependency conflict, or retry npm ERR! this command with --force, or --legacy-peer-deps npm ERR! to accept an incorrect (and potentially broken) dependency resolution. npm ERR! npm ERR! See C:\Users\someone\AppData\Local\npm-cache\eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\someone\AppData\Local\npm-cache_logs\2022-12-30T20_50_43_182Z-debug-0.log
> 
> it seems like it doesnt work with vite 4.0.0? is there any way to make it work with it?

This problem is caused by vite4. x. Please upgrade to v0.0.5 to solve this problem
