### ISSUE TITLE
把 example 目录单独下载下来，并使用 `pnpm` 安装会报 `solid-mdx` 缺失

### ISSUE THREAD

**Issue by dream2023** [xbmlz/vite-plugin-solid-markdown#3]
![1674224144076](https://user-images.githubusercontent.com/19297757/213719325-af3085e1-6862-4620-a657-d34cd6798189.png)

**Comment by xbmlz** [comment]
example 是使用 `workspace:*` 进行依赖的，单独下载是无法运行的，可以把`workspace:*`替换成具体的版本后，然后npm i

**Comment by dream2023** [comment]
> example 是使用 `workspace:*` 进行依赖的，单独下载是无法运行的，可以把`workspace:*`替换成具体的版本后，然后npm i

我没说清楚：

- 下载了整个项目
- 单独把 example 目录挪到外面
- 把 package.json 中 `vite-plugin-solid-markdown` 替换为 `0.0.5`
- pnpm install
- pnpm run dev


报错

**Comment by xbmlz** [comment]
> > example 是使用 `workspace:*` 进行依赖的，单独下载是无法运行的，可以把`workspace:*`替换成具体的版本后，然后npm i
> 
> 我没说清楚：
> 
> * 下载了整个项目
> * 单独把 example 目录挪到外面
> * 把 package.json 中 `vite-plugin-solid-markdown` 替换为 `0.0.5`
> * pnpm install
> * pnpm run dev
> 
> 报错

这是个pnpm-workspace项目，一部分依赖的在root的package.json，根据报错提示，安装缺少的依赖到example项目就可以了

**Comment by dream2023** [comment]
> > > example 是使用 `workspace:*` 进行依赖的，单独下载是无法运行的，可以把`workspace:*`替换成具体的版本后，然后npm i
> > 
> > 
> > 我没说清楚：
> > 
> > * 下载了整个项目
> > * 单独把 example 目录挪到外面
> > * 把 package.json 中 `vite-plugin-solid-markdown` 替换为 `0.0.5`
> > * pnpm install
> > * pnpm run dev
> > 
> > 报错
> 
> 这是个pnpm-workspace项目，一部分依赖的在root的package.json，根据报错提示，安装缺少的依赖到example项目就可以了

额。。。事实上单独安装，不使用 example 也会出错，你可以试试，不使用 `solid-start`. 

不过我将代码直接拷贝到目录下就行了。
